services:
  - type: web
    name: flowise-docker-render
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    repo: https://github.com/FlowiseAI/Flowise
    branch: main
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key : DATABASE_PATH
        value: /opt/render/.flowise
      - key : SECRETKEY_PATH
        value: /opt/render/.flowise/
    disk:
      name: flowise-disk
      mountPath: /opt/render/.flowise
      sizeGB: 1

   # A Docker web service
  - type: web
    name: zep
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-cloud:latest
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8000
      - key: ZEP_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres
          property: connectionString
      - key: ZEP_NLP_SERVER_HOSTPORT
        fromService:
          name: zep-nlp
          type: pserv
          property: hostport
      - key: ZEP_OPENAI_API_KEY
        sync: false
  - type: pserv
    name: zep-nlp
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-nlp-server:latest

databases:
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: [] # only allow internal connections


  
